# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmn < Formula
  desc "A lightweight, non-interactive Gemini CLI written in Go"
  homepage "https://github.com/tomohiro-owada/gmn"
  version "0.38.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomohiro-owada/gmn/releases/download/v0.38.1/gmn_0.38.1_darwin_amd64.tar.gz"
      sha256 "a56fa593c885b726be0385c9f15bd261033d7e8d2474ce7cd56b96913600d590"

      define_method(:install) do
        bin.install "gmn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomohiro-owada/gmn/releases/download/v0.38.1/gmn_0.38.1_darwin_arm64.tar.gz"
      sha256 "57db49777f01d913dfb25582da409590d7116109cb2c56a185a572ce7361562b"

      define_method(:install) do
        bin.install "gmn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomohiro-owada/gmn/releases/download/v0.38.1/gmn_0.38.1_linux_amd64.tar.gz"
      sha256 "edb7445bdf63a7589ee4c8d57f9a46ad78c2e45fcfb89719938e5bbad0742dcd"
      define_method(:install) do
        bin.install "gmn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomohiro-owada/gmn/releases/download/v0.38.1/gmn_0.38.1_linux_arm64.tar.gz"
      sha256 "a699f1a68576c2d43e40532a7be16d937072401590779e07bda86480d1f3f299"
      define_method(:install) do
        bin.install "gmn"
      end
    end
  end

  test do
    system "#{bin}/gmn", "--version"
  end
end
